export default {
	THEME_CHANGE:'THEME_CHANGE',
	THEME_INIT:'THEME_INIT',
	DISCOVER_REFRESH:'DISCOVER_REFRESH',
	DISCOVER_REFRESH_FAIL:'DISCOVER_REFRESH_FAIL',
	DISCOVER_REFRESH_SUCCESS:'DISCOVER_REFRESH_SUCCESS',
	DISCOVER_LOAD_MORE_SUCCESS:'DISCOVER_LOAD_MORE_SUCCESS',
	DISCOVER_LOAD_MORE_FAIL:'DISCOVER_LOAD_MORE_FAIL',
	DISCOVER_LOAD_MORE_LOADING:'DISCOVER_LOAD_MORE_LOADING',
}